self-hosted-runner:
  # Labels of self-hosted runners (array(string))
  labels:
    - m6i-public # 3.6 CPU, 14.2 GB of memory (1 m6i.xlarge machine - 1 runner/node)
    - eks-migration # 1.1 CPU, 4.5 GB of memory (1/3 m6i.xlarge machine - 3 runners/node). Used solely for eks deployment jobs
    - test # like dind, 1 replica. use for testing
    - m6i-spot
