- id: ltex
  name: LTeX grammar check
  language: script
  entry: ltex/ltex.sh
  verbose: true
  types_or: ['markdown', 'mdx']

- id: actionlint
  name: Lint Github workflows
  language: docker_image
  entry: rhysd/actionlint:1.7.7
  files: ^\.github/workflows/.*\.(yml|yaml)$

- id: hadolint
  name: Lint Dockerfiles
  language: docker_image
  entry: hadolint/hadolint:v2.12.1-beta-debian hadolint
  files: Dockerfile
