- id: ltex
  name: LTeX grammar check
  language: script
  entry: ltex/ltex.sh
  verbose: true
  types_or: ['markdown', 'mdx']

- id: actionlint
  name: Lint Github workflows
  language: docker_image
  entry: rhysd/actionlint:1.6.26
  files: ^\.github/workflows/.*\.yml$
